# Generated by Django 2.2.5 on 2019-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='definition',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='term',
            name='example',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='term',
            name='url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
